location: .gitman
sources:
  - repo: https://github.com/ctu-pairs/pairs_gazebo_common_resources.git
    name: pairs_gazebo_common_resources
    rev: depth-3dlidar-fix
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: pairs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-pairs/pairs_uav_gazebo_testing.git
    name: pairs_uav_gazebo_testing
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: pairs_uav_gazebo_testing
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-pairs/px4_firmware.git
    name: px4_firmware
    rev: 1.13.2-dev
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: px4_firmware
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-pairs/px4_sitl_gazebo.git
    name: mavlink_sitl_gazebo
    rev: firmware_1.13.2-deb
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mavlink_sitl_gazebo
    scripts:
      - git submodule update --init --recursive
